language: ruby

dist: focal

services:
  - postgresql

cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  # jruby config pending
  # - jruby

env:
  - "HAML=1"
  - "NO_HAML=0"

gemfile:
  - Gemfile
